language: php

php:
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: STYLE
      install:
        - composer config github-oauth.github.com $GITHUB_OAUTH
        - travis_retry composer install --prefer-dist --no-interaction --no-suggest
      script: vendor/bin/php-cs-fixer fix . --dry-run --diff

  allow_failures:
    - php: nightly

install:
  - composer config github-oauth.github.com $GITHUB_OAUTH
  - composer remove friendsofphp/php-cs-fixer --dev --no-update --no-interaction
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit
